baseURL = "https://fabien-prudhomme.github.io/"
languageCode = "fr-fr"
title = "wiza-tech"
theme = "wizaplace"

[taxonomies]
  category = "categories"
  tag = "tags"

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "06/12/2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"

[[menu.nav]]
name    = "Liste des articles"
url     = "blog"
weight  = 5

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "Blog technique wizaplace"
# button
btn     = true
btnText = "Site institutionnel"
btnURL  = "https://www.wizaplace.com/fr/"

# flip text
[[params.banner.flipText]]
title   = "de la veille"
[[params.banner.flipText]]
title   = "de la technique"
[[params.banner.flipText]]
title   = "des POC"


# Portfolio Section On Homepage
[params.blog]
enable  = true
title   = "Derniers articles"
nbArticles= 3

# social icon
[[params.socialIcon]]
icon = "ion-social-twitter"
url = "https://twitter.com/WizaTech"

[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://www.facebook.com/wizaplace/"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "https://www.linkedin.com/company/wizaplace"
